### PR TITLE
add event enum type

### PR DESCRIPTION
**Pull request by sanette**
https://github.com/dbuenzli/tsdl/issues/53

WARNING I could **not** compile with this PR because I don't have SDL 2.0.9 which is now required by tsdl because of SDL_DISPLAYEVENT etc.

(ubuntu 18.04 ships with SDL 2.0.8)

### CODE REVIEW

**Comment by fccm** [comment]
It's quite easy to install several versions of the same lib on Linux, you can compile the sources of SDL2 with:
```
sh configure --prefix=/tmp/sdl2
```
then you can define some environment variables:
```
export CPATH=/tmp/sdl2/lib/include
export LIBRARY_PATH=/tmp/sdl2/lib
export LD_LIBRARY_PATH=/tmp/sdl2/lib
export PKG_CONFIG_PATH=/tmp/sdl2/lib/pkgconfig
export PATH=/tmp/sdl2/bin:$PATH
```

**Comment by fccm** [comment]
It's possible to use the git option `--ignore-all-space` (`-w` for short) to read the diff and ignore the indentation changes in this PR, so that you can more easily check that no variant was changed:
```
git diff -w 3ba92bf37 45963588c
```
I compiled this branch and ran the test file `./_build/test/sdlevents.native` which uses the function `Sdl.Event.enum` on line 37. Everything seems OK with this PR, for me it seems legitimate to want a type there.

From a style point of view, I don't think there was a need to indent the variants for this type `Event.enum`, and also there is a space added on an empty line at line 3080 in src/tsdl.mli

**Comment by dbuenzli** [comment]
Thanks @fccm for the review. Since I didn't want to bother @sanette with styling issues I directly added something in a0fb1cd5f95446e1aef2. Thanks @sanette for the report and PR.

**Comment by sanette** [comment]
thanks! sorry I didn't have the time to reply to anything in the last couple of weeks...

**Pull request closed without merging**
