### PR TITLE
Fix#32

### PR DESCRIPTION
**Pull request by sanette**
fix load_wav_rw segfault:

the "freesrc" int parameter was forgotten in calling SDL_LoadWAV_RW, leading to segault.

Please note I didn't try to compile and use this very version because I have SDL 2.0.3
(from ubuntu)
It does compile and work if I base it on tsdl 0.9.1

(Please forgive me if the git history is messy/buggy, I'm a git newby. Only a trivial modif of tsdl.ml should be taken into account. Ignore the rest)

### CODE REVIEW

**Comment by zapashcanon** [comment]
`git rebase -i HEAD~12`

Then, just replace `pick` by `fixup` on the first 12 commits, save and close.
Then, maybe `git rebase --continue`. (not sure if it's necessary when you only do fixups)

Finally, `git push -f`.

**Comment by sanette** [comment]
@zapashcanon: thanks for the info, I will try as soon as I have some time.

But isn't all of this a bit too much for only 2 trivial changes in 2 lines ? It would maybe save everybody's time to just do it manually.
(or maybe you can squash in order to ignore my history ?)

**Comment by sanette** [comment]
ok, I tried this (to learn git) but it didn't work. My commits are mixup with Daniel's, so selecting the first 12 didn't work, and I had an error 
error: impossible d'appliquer baee393... Use topkg.
BREF... my git history is completely scambled now ;)
I will simply create a new branch, it will be cleaner...

**Comment by sanette** [comment]
Done (https://github.com/dbuenzli/tsdl/pull/35).
I am closing this one.

**Comment by zapashcanon** [comment]
Yep indeed. I though you wrote 13 commits, didn't saw that they were copy/paste from other commits..

**Pull request closed without merging**
