### PR TITLE
Added SDL_QueueAudio.

### PR DESCRIPTION
**Pull request by eriklovlie**
Wasn't sure what style you preferred in the test so I tried to not deviate much from the existing test_audio.ml.

### CODE REVIEW

**Comment by dbuenzli** [comment]
Thanks. I seems however that the audio queue API has a few more functions, would you mind also providing bindings to `SDL_DequeueAudio()`, `SDL_GetQueuedAudioSize()`, `SDL_ClearQueuedAudio()` ? You don't need to open another PR, just push on that one.

**Comment by eriklovlie** [comment]
Yeah, good point. This occurred to me also but this QueueAudio function seemed useful on its own. But sure, I can try to add the others.

**Comment by eriklovlie** [comment]
Added the other functions that I could see being related.

**Comment by dbuenzli** [comment]
Thanks for the additions !

So your patches are in squashed as  fee3d953aede59d36a45f6d258db40225eb67e3c, they where slightly reformatted by 27162f3d89c515889df756cdec210b043f74251e to stick to the 80 columns rule. Finally in 195d7c3a7a3a6fe89ee19d52356c2cf1f35f3b26 I changed the return type of 
`Sdl.{dequeue_audio,get_queued_audio_size}` to an OCaml `int` instead of an `uint32`. The reason is that this is the integer type supported by the underlying OCaml abstraction (bigarrays) that interacts with the SDL API. 

If you can confirm me that all of this works for you (`opam pin tsdl --dev`) then I can make a new release.

**Comment by eriklovlie** [comment]
Just checked and seems to work fine!

**Pull request closed without merging**
